steps:
  # This step package and push the helm chart to a repo
  - name: gcr.io/$PROJECT_ID/helm
    id: Package and push chart
    entrypoint: /bin/sh
    env:
      - HELM_EXPERIMENTAL_OCI=1
    args:
      - '-c'
      - |
        helm package foodapp/ && \
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://asia-southeast1-docker.pkg.dev && \
        helm push foodapp-$TAG_NAME.tgz oci://asia-southeast1-docker.pkg.dev/$PROJECT_ID/helm-repo

  # This step installs the packaged helm chart into GKE cluster
  - name: gcr.io/$PROJECT_ID/helm
    id: Install helm chart into cluster for staging
    entrypoint: /bin/sh
    env:
    - HELM_EXPERIMENTAL_OCI=1
    args:
      - '-c'
      - |
      gcloud container clusters get-credentials staging --zone asia-southeast1 && \
      kubectl create ns foodapp && \
      helm install foodapp /workspace/foodapp-$TAG_NAME.tgz -n foodapp



