apiVersion: v1
kind: Service
metadata:
  name: {{ include "foodapp.fullname" . }}
  labels:
    {{- include "foodapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "foodapp.selectorLabels" . | nindent 4 }}
